### PR TITLE
wheels 1.3.x compatibility

### PR DESCRIPTION
**Pull request by chapmandu**
Added the private $appKey function so coldroute can be initialised during wheels 1.3 thread-safe reload

### CODE REVIEW

**Comment by dhumphreys** [comment]
So bring me up to speed, cause I haven't dug through my email on this issue yet. The application scope for wheels is now threadsafe on reloads? The $appKey function tells which scope to use? It looks like this has been implemented well with the following concerns and questions:
- $appKey is defined twice. Is it also defined in wheels 1.3?
- is this backwards compatible with 1.1.x?
- is there a more efficient way to do this rather than the same StructKeyExists call many many times in the same request?
- there are a lot of meaningless whitespace changes in this commit that should probably be removed

Thanks for submitting this request and keeping the interest in coldroute alive :)

**Comment by chapmandu** [comment]
1. $appKey is defined twice. Is it also defined in wheels 1.3?
   ... Yes, the core function isn't available to the plugin. Defining it twice does bother me but Mapper.cfc and coldroute.cfc seem quite insular. I could create a single cfinclude, though it seems kludgier than just defining it twice.
2. is this backwards compatible with 1.1.x?
   ... It is now.. I had to make one of the $wheelsKey functions public.
3. is there a more efficient way to do this rather than the same StructKeyExists call many many times in the same request? 
   ... I'm not sure.. I started by trying to write to the application variable but I couldn't make it work with the thread-safe reloading. It "seems" that at some point during the loading of plugins the wheels 'scope' changes from "$wheels" to "wheels"
4. there are a lot of meaningless whitespace changes in this commit that should probably be removed
   ... That was my code editor's "strip whitespace" function.. I've put the whitespace back in.

I'm very open to suggestions to improve.

**Comment by farism** [comment]
Any plans to merge this PR?

**Comment by dhumphreys** [comment]
@farism I'll go ahead and merge this if you will test it to confirm. I am not very actively maintaining coldroute since I don't work in a coldfusion shop anymore. Sorry for the delays.

**Comment by chapmandu** [comment]
I've been using the changes in production with wheels 1.3.x for months with no issues so far.. Thanks @dhumphreys

**Pull request merged**
