### PR TITLE
Namespaced provides

### PR DESCRIPTION
**Pull request by chrisdpeters**
This allows for you to use custom templates like `/api/members/index.json.cfm`. Before this change, it was looking for `/api.Members/index.json.cfm`.

If this solution isn't appropriate, at least you're aware of the issue. Feel free to make it better, of course.

### CODE REVIEW

**Comment by dhumphreys** [comment]
Chris,

I believe that this falls into the category of changes that I like to think of as "changes to the core to support dot syntax in controller names." This obviously relates to making coldroute namespaces work correctly in wheels, but I don't know that placing it in the coldroute plugin is the answer.

Nine months ago I made a commit to fix all of these places in the core [here](https://github.com/cfwheels/cfwheels/commit/aea8e3212136512102255fdf9a1e67417c25acd2). I obviously missed the renderWith() method. Perhaps this should be a followup commit to the commit I placed back then. Unfortunately I don't think that those changes have been included in any releases yet. If you also feel that that is the best route to go, one of us can commit your changes into the core, and I will close this pull request.

As a side note, I noticed that you merged from _upstream/master_ into your develop branch. Commits from _master_ in this repo are considered "release" and should not be merged back into _develop_, since _master_ is what gets directly tagged for releases. _master_ is actually a snapshot of _develop_ commits and should already include _develop_ work anyway. The commits you merged were actually hotfixes for the 0.1.1 release, which were already merged into _develop_ way back. I'm doing all of this according [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) workflow, and I highly recommend that you check it out. It is an great read on an excellent way to manage a software project with git.

**Comment by dhumphreys** [comment]
And I have a great solution for view pathing in the long run in cfwheels. When a controller is initialized, it should keep an array of view paths in its variables scope, for example, `variables.wheels.$class.viewPath = [];` By default, this should be set to something like `wheels_root & "/views/" & ListChangeDelims(controller_name, ".", "/")`. But the default is just appended to the view path array. In this way, you can construct view inheritance. Because extended controllers would just keep appending to the view path array. Every time renderPage(), renderPartial(), includePartial(), renderWith(), or even helper includes are performed, they would evaluate all of the view paths for a specific controller in order. There are a lot of possibilities with this approach, and you'd only have to handle this ListChangeDelims() business in a single place: where the view path is initially set.

You could set up a controller `AbstractNote.cfc` and have `ItemNote.cfc` extend it. It would then have access to all of the partials, views and helpers of `AbstractNote.cfc`, but be able to create its own view files as well, which would have precedence over the extended controller.

**Comment by chrisdpeters** [comment]
Our clients can't really afford to pay us for mucking with the edge release on their projects, so I need some way to have this stuff work in the plugin on version 1.1.7. I have a forked version of the plugin running right now with some of James's changes along with this one. Works well for our project, but obviously looking forward to it being in the core instead.

I'll go ahead and close this pull request. At least it's documented somewhere that something needs to be changed.

Sorry about the branching mistake. I'll check out the link for sure!

**Comment by dhumphreys** [comment]
If you need this support, then I can definitely add it to the plugin. My only problem with it is that by copying the function into a coldroute override, any changes that are made to that function cfwheels will be voided by the presence of the coldroute plugin. I completely understand not wanting to wait on core changes though.

We are having the same issue with our main client application, which is still running 1.1.1 because of the huge number of manual patches that we have to transfer to each new wheels version when we upgrade. We are now trying to justify most of these changes in the wheels core or split them out into a project-specific plugin for our app. We may have to go to either edge wheels or cherry pick commits into a private branch to move forward, rather than moving dozens of patches manually and hoping something doesn't break our application.

Anyway, let me know if you really need this in the plugin and I'll be happy to include it.

**Comment by chrisdpeters** [comment]
I think this either needs to be included in the plugin, or a supporting plugin needs to be created for Wheels 1.1 users. I think the plugin would be more useful if we lived with the reality that there is no Wheels 1.2 or 2.0 yet.

For example, I am doing a screencast about ColdRoute this afternoon, and I'm going to need to include weird instructions on how to get it working so namespaces can be done. I'm thinking about creating the supporting plugin so at least I can point people to a URL to download without asking them to hack the core.

**Comment by dhumphreys** [comment]
Does this single change fix the problem? If so, I can have it merged for you by 4:00pm.

**Comment by chrisdpeters** [comment]
The version of the plugin that I'm using is from James's repo, so I think more work needs to be done than just this.

**Comment by dhumphreys** [comment]
James still has a pull request open at #22. I may consider pulling that in, although I haven't been able to look at all of the work he has done. Since it is all work on coldroute.cfc, it looks like it is 100% wheels compatibility work. It's unfortunate that the copy-then-modify method has to be done to get things compatible with wheels. We will have to be careful about this and remove all of the overrides as soon as the namespace compatibility changes are in the main wheels release.

Do I also need to pull in your commit?

**Comment by dhumphreys** [comment]
All merged in. You may want to do a hard reset from your develop branch to my develop branch to get your commit history right since I removed the master merge you did.

Let me know if the code all works correctly. And good luck on the screencast! I'm looking forward to seeing it.

**Comment by chrisdpeters** [comment]
Thanks Don. Time to get this stuff moving.

**Pull request closed without merging**
